# Generated by Django 5.2.9 on 2025-12-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('totems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=500, verbose_name='Destino')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('search_count', models.IntegerField(default=0, verbose_name='Pesquisas')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='Última Pesquisa')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_destinations', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Destino Popular',
                'verbose_name_plural': 'Destinos Populares',
                'ordering': ['-search_count'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('sessions_count', models.IntegerField(default=0, verbose_name='Sessões')),
                ('interactions_count', models.IntegerField(default=0, verbose_name='Interações')),
                ('routes_searched', models.IntegerField(default=0, verbose_name='Rotas Pesquisadas')),
                ('avg_session_duration', models.IntegerField(default=0, verbose_name='Duração Média (s)')),
                ('peak_hour', models.IntegerField(null=True, verbose_name='Horário de Pico')),
                ('totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='totems.totem')),
            ],
            options={
                'verbose_name': 'Estatística Diária',
                'verbose_name_plural': 'Estatísticas Diárias',
                'ordering': ['-date'],
                'unique_together': {('totem', 'date')},
            },
        ),
    ]
