# Generated by Django 5.2.9 on 2025-12-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('totems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Origem Lat')),
                ('origin_lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Origem Lng')),
                ('destination_lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Destino Lat')),
                ('destination_lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Destino Lng')),
                ('destination_name', models.CharField(max_length=500, verbose_name='Nome Destino')),
                ('transport_mode', models.CharField(max_length=20, verbose_name='Modo')),
                ('distance_meters', models.IntegerField(null=True, verbose_name='Distância (m)')),
                ('duration_seconds', models.IntegerField(null=True, verbose_name='Duração (s)')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Pesquisado em')),
                ('totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_searches', to='totems.totem')),
            ],
            options={
                'verbose_name': 'Pesquisa de Rota',
                'verbose_name_plural': 'Pesquisas de Rotas',
                'ordering': ['-searched_at'],
            },
        ),
    ]
