# Generated by Django 5.2.9 on 2025-12-14 16:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('address', models.CharField(max_length=500, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=200, verbose_name='Bairro')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localização')),
                ('screen_orientation', models.CharField(choices=[('portrait', 'Retrato'), ('landscape', 'Paisagem')], default='portrait', max_length=20, verbose_name='Orientação')),
                ('brightness', models.IntegerField(default=80, verbose_name='Brilho (%)')),
                ('volume', models.IntegerField(default=50, verbose_name='Volume (%)')),
                ('session_timeout', models.IntegerField(default=60, verbose_name='Timeout (segundos)')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('maintenance', 'Em Manutenção'), ('offline', 'Offline')], default='active', max_length=20, verbose_name='Status')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Último Heartbeat')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP')),
                ('installed_at', models.DateField(blank=True, null=True, verbose_name='Instalado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totems', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Totem',
                'verbose_name_plural': 'Totems',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TotemSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='Session ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('language', models.CharField(default='pt-BR', max_length=10, verbose_name='Idioma')),
                ('interactions_count', models.IntegerField(default=0, verbose_name='Interações')),
                ('totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='totems.totem')),
            ],
            options={
                'verbose_name': 'Sessão do Totem',
                'verbose_name_plural': 'Sessões dos Totems',
                'ordering': ['-started_at'],
            },
        ),
    ]
