# Generated by Django 5.2.9 on 2025-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='background_color',
            field=models.CharField(blank=True, default='', help_text='Gradiente CSS ou cor sólida (ex: linear-gradient(135deg, #1a1a2e, #16213e))', max_length=100, verbose_name='Cor de Fundo'),
        ),
        migrations.AddField(
            model_name='totem',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Imagem de fundo para área de interação', null=True, upload_to='totems/backgrounds/', verbose_name='Imagem de Fundo'),
        ),
        migrations.AddField(
            model_name='totem',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo PNG para exibir no cabeçalho (substitui o nome da cidade)', null=True, upload_to='totems/logos/', verbose_name='Logo'),
        ),
    ]
