# Generated by Django 5.2.9 on 2025-12-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0002_add_branding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='theme',
            field=models.CharField(choices=[('player', 'Player (Somente Anúncios)'), ('tomipro', 'TOMI Pro (Completo)'), ('tomi', 'TOMI (Clássico)'), ('dashboard', 'Dashboard'), ('touch', 'Touch'), ('simple', 'Simples')], default='player', help_text='Layout visual do totem', max_length=20, verbose_name='Layout/Tema'),
        ),
    ]
