# Generated by Django 5.2.9 on 2025-12-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0003_add_theme_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, 'Superior Esquerdo'), (2, 'Superior Direito'), (3, 'Inferior Esquerdo'), (4, 'Inferior Direito')], verbose_name='Posição')),
                ('block_type', models.CharField(choices=[('featured_event', 'Evento em Destaque'), ('events_list', 'Lista de Eventos'), ('news', 'Notícias'), ('pois', 'Pontos de Interesse'), ('weather', 'Clima'), ('map', 'Mapa'), ('custom', 'Conteúdo Personalizado'), ('image', 'Imagem'), ('video', 'Vídeo')], max_length=30, verbose_name='Tipo de Bloco')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, default='', max_length=300, verbose_name='Subtítulo')),
                ('background_color', models.CharField(blank=True, default='#ffffff', max_length=50, verbose_name='Cor de Fundo')),
                ('text_color', models.CharField(blank=True, default='#000000', max_length=50, verbose_name='Cor do Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='totems/blocks/', verbose_name='Imagem')),
                ('content_html', models.TextField(blank=True, default='', help_text='HTML personalizado para blocos do tipo "custom"', verbose_name='Conteúdo HTML')),
                ('link_url', models.URLField(blank=True, default='', verbose_name='Link')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações específicas do tipo de bloco (ex: limite de itens, filtros)', verbose_name='Configuração')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.IntegerField(default=0, help_text='Para ordenação dentro da mesma posição', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='totems.totem')),
            ],
            options={
                'verbose_name': 'Bloco de Conteúdo',
                'verbose_name_plural': 'Blocos de Conteúdo',
                'ordering': ['totem', 'position', 'order'],
                'unique_together': {('totem', 'position')},
            },
        ),
    ]
