# Generated by Django 5.2.9 on 2025-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0004_add_content_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='video',
            field=models.FileField(blank=True, help_text='Arquivo de vídeo para blocos do tipo "video" (MP4 recomendado)', null=True, upload_to='totems/blocks/videos/', verbose_name='Vídeo'),
        ),
    ]
