# Generated by Django 5.2.9 on 2025-12-14 16:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#3182ce', max_length=7, verbose_name='Cor')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
                'unique_together': {('city', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagem')),
                ('venue', models.CharField(max_length=300, verbose_name='Local')),
                ('address', models.CharField(max_length=500, verbose_name='Endereço')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('start_date', models.DateTimeField(verbose_name='Data Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Dia Inteiro')),
                ('price', models.CharField(blank=True, default='Gratuito', max_length=100, verbose_name='Preço')),
                ('url', models.URLField(blank=True, verbose_name='Link')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagem')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('display_start', models.DateTimeField(blank=True, null=True, verbose_name='Exibir a partir de')),
                ('display_end', models.DateTimeField(blank=True, null=True, verbose_name='Exibir até')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Subtítulo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('publish_at', models.DateTimeField(verbose_name='Publicar em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('poi_type', models.CharField(choices=[('restaurant', 'Restaurante'), ('hotel', 'Hotel'), ('attraction', 'Atração Turística'), ('shopping', 'Compras'), ('hospital', 'Hospital'), ('pharmacy', 'Farmácia'), ('police', 'Polícia'), ('transport', 'Transporte'), ('bank', 'Banco'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pois/', verbose_name='Imagem')),
                ('address', models.CharField(max_length=500, verbose_name='Endereço')),
                ('neighborhood', models.CharField(blank=True, max_length=200, verbose_name='Bairro')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localização')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('opening_hours', models.JSONField(blank=True, default=dict, verbose_name='Horário de Funcionamento')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Ponto de Interesse',
                'verbose_name_plural': 'Pontos de Interesse',
                'ordering': ['name'],
            },
        ),
    ]
