# Generated by Django 5.2.9 on 2025-12-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('tenants', '0001_initial'),
        ('totems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Fim')),
                ('weekdays', models.JSONField(default=list, verbose_name='Dias da Semana')),
                ('all_totems', models.BooleanField(default=True, verbose_name='Todos os Totems')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='tenants.city')),
                ('totems', models.ManyToManyField(blank=True, related_name='playlists', to='totems.totem')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('ad', 'Publicidade'), ('weather', 'Clima'), ('news', 'Notícias'), ('events', 'Eventos'), ('rss', 'Feed RSS'), ('html', 'HTML Personalizado'), ('clock', 'Relógio'), ('qrcode', 'QR Code')], max_length=20, verbose_name='Tipo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='playlist/', verbose_name='Imagem')),
                ('video_url', models.URLField(blank=True, verbose_name='URL do Vídeo')),
                ('content_url', models.URLField(blank=True, verbose_name='URL do Conteúdo')),
                ('html_content', models.TextField(blank=True, verbose_name='Conteúdo HTML')),
                ('duration', models.IntegerField(default=10, verbose_name='Duração (segundos)')),
                ('transition', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('none', 'Nenhuma')], default='fade', max_length=20, verbose_name='Transição')),
                ('background_color', models.CharField(default='#000000', max_length=7, verbose_name='Cor de Fundo')),
                ('text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do Texto')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.playlist')),
            ],
            options={
                'verbose_name': 'Item da Playlist',
                'verbose_name_plural': 'Itens da Playlist',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('url', models.URLField(verbose_name='URL do Feed')),
                ('last_fetched', models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização')),
                ('cached_content', models.JSONField(default=list, verbose_name='Conteúdo em Cache')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_feeds', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Feed RSS',
                'verbose_name_plural': 'Feeds RSS',
            },
        ),
    ]
