# Generated by Django 5.2.9 on 2025-12-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_playlist_playlistitem_rssfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='item_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('ad', 'Publicidade'), ('weather', 'Clima'), ('news', 'Notícias'), ('events', 'Eventos'), ('rss', 'Feed RSS'), ('html', 'HTML Personalizado'), ('clock', 'Relógio')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='transition',
            field=models.CharField(default='fade', max_length=20, verbose_name='Transição'),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='cached_content',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
