# Generated by Django 5.2.9 on 2025-12-14 16:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localização')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Fuso Horário')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cities/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#1a365d', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#2c5282', max_length=7, verbose_name='Cor Secundária')),
                ('default_language', models.CharField(default='pt-BR', max_length=5, verbose_name='Idioma Padrão')),
                ('available_languages', models.JSONField(default=list, verbose_name='Idiomas Disponíveis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Visualizador')], max_length=20, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='tenants.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador da Cidade',
                'verbose_name_plural': 'Administradores das Cidades',
                'unique_together': {('user', 'city')},
            },
        ),
    ]
