# Generated by Django 5.2.9 on 2025-12-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('totems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('ad_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=20, verbose_name='Tipo')),
                ('file', models.FileField(upload_to='ads/', verbose_name='Arquivo')),
                ('duration', models.IntegerField(default=10, verbose_name='Duração (s)')),
                ('click_url', models.URLField(blank=True, verbose_name='URL de Clique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Criativo',
                'verbose_name_plural': 'Criativos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_at', models.DateTimeField(auto_now_add=True, verbose_name='Exibido em')),
                ('duration_viewed', models.IntegerField(default=0, verbose_name='Tempo Visualizado (s)')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='advertising.adcreative')),
                ('totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='totems.totem')),
            ],
            options={
                'verbose_name': 'Impressão',
                'verbose_name_plural': 'Impressões',
                'ordering': ['-displayed_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisers', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Anunciante',
                'verbose_name_plural': 'Anunciantes',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('active', 'Ativa'), ('paused', 'Pausada'), ('ended', 'Finalizada')], default='draft', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(verbose_name='Início')),
                ('end_date', models.DateTimeField(verbose_name='Fim')),
                ('all_totems', models.BooleanField(default=True, verbose_name='Todos os Totems')),
                ('schedule', models.JSONField(blank=True, default=dict, verbose_name='Horários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertising.advertiser')),
                ('totems', models.ManyToManyField(blank=True, related_name='campaigns', to='totems.totem')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adcreative',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='advertising.campaign'),
        ),
    ]
