# Generated by Django 5.2.9 on 2025-12-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Alerta'), ('danger', 'Perigo'), ('extreme', 'Extremo')], max_length=20, verbose_name='Severidade')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo de Evento')),
                ('source', models.CharField(max_length=100, verbose_name='Fonte')),
                ('starts_at', models.DateTimeField(verbose_name='Início')),
                ('ends_at', models.DateTimeField(null=True, verbose_name='Fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Alerta Climático',
                'verbose_name_plural': 'Alertas Climáticos',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura')),
                ('feels_like', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sensação')),
                ('humidity', models.IntegerField(verbose_name='Umidade (%)')),
                ('pressure', models.IntegerField(verbose_name='Pressão (hPa)')),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Vento (m/s)')),
                ('wind_direction', models.IntegerField(verbose_name='Direção Vento')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('icon', models.CharField(max_length=10, verbose_name='Ícone')),
                ('visibility', models.IntegerField(null=True, verbose_name='Visibilidade (m)')),
                ('clouds', models.IntegerField(null=True, verbose_name='Nuvens (%)')),
                ('sunrise', models.DateTimeField(null=True, verbose_name='Nascer do Sol')),
                ('sunset', models.DateTimeField(null=True, verbose_name='Pôr do Sol')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Obtido em')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='tenants.city')),
            ],
            options={
                'verbose_name': 'Dados Climáticos',
                'verbose_name_plural': 'Dados Climáticos',
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
    ]
